### ISSUE TITLE
Nice initiative!

### ISSUE THREAD

**Issue by swanav** [Accounting-Companion/TallyConnector#1]
Hi @saivineeth100!

This project looks promising! I have been searching for a long time for a project on these principles, but haven't been able to find any. I had almost made up my mind to create a project myself for the same purpose, but I could never get a hold of the Tally XML API to a satisfactory level.

I would like to use this project and also would like to help develop this along with you if you want.

Do let me know if this sounds worth exploring to you.  If so, please share a list of pending TODO items and I'll see if I can help.

Looking forward to your response!

Thanks!

**Comment by saivineeth100** [comment]
Hi @swanav 
I also searched for longtime and didn't found object oriented wrapper for Tally XML API so I created one
Yes you can use in your projects and also contribute to this project

I am planning make this library cover all types of xml API provided by Tally without using any raw XML
Following are pending

****Todo List****
- Company, Attendance, Employee Group & Employees models needs to be completed
- Check whether all fields for all objects(Ledger, Group etc.)
- Add support for VBA(I already created separate branch for .net framework for this-Now I can add reference in VBA but I cannot use functions in VBA) 
- Add Detailed Documentation for c#, VB, VBA, Python()
If you can help me in completing any of these It will be helpful

And any suggestions in making this library more performant are always welcome

**Comment by swanav** [comment]
Hi @saivineeth100,

I have spent some time trying to figure out the library. I'll admit I have never worked with Microsoft's C# and its sister languages, so I am not familiar with the .NET eco system at all. 

Although, I was able to get a started project set-up which referenced this project and was able to extract some data from my Tally Database. Simple stock queries and stuff, nothing extensive.

But not being very familiar with C# and never having to work on it, rules out C#, VB and VBA for me. I tried using Python.NET to integrate the DLL in a python module, but it seems like the namespaces are not being imported from the DLL. Have you tried out any experiments using Python? Any pointers for me?

I can certainly try learning C#, but I doubt I'll be able to integrate that in my current projects and other use cases in the longer run. 
I have a fair amount of experience in Node.JS and I feel if we can somehow get the integration to interact with a Node.JS runtime, it would certainly allow for a lot of server-side integrations with this library.


> Add Detailed Documentation

I can definitely try adding documentation for the blocks that I can manage to get working!

**Comment by saivineeth100** [comment]
Hello @swanav 

Great to hear that you was able to play with tally using Tally Connector

In order to use this library in pythonnet downloaded from pypi you need to use Tallyconnector build with .Net Framework, which I don't recommend as I got some errors while converting to json, so better install pythonnet directly from github it supports .net5
you can follow [this guide](https://blog.saivineeth.com/en/TallyConnector/Python-Tally-Integration_Getting-Started/)

I am planning to create a convert this project to Typescript, Java and Dart also, but not now.
Server side integration is a bad idea as connecting to Tally from server is not possible, because PC on which tally runs doesn't have static IPs.

Since you have experience in Node js you can also contribute in converting this library to typescript

**Comment by sanketgroup** [comment]
Hi Sai Vineeth
This is really amazing startup.
Appreciate your efforts to help the community.
In order to use it I did following steps: correct me where I am wrong.

I downloaded your c# project and "Build". That generated TallyConnector.dll in the project folder.
I copied that DLL into my actual project and added as reference.
But then after when I coded the lines as you described,  visual studio shows an error.

Is this any sample c# windows form project which works with default tally settings which I can try.

Pls let me know.

Thanking you
Sanket

**Comment by saivineeth100** [comment]
@sanketgroup 
create a new issue instead of commenting on issue
It would be better if you provide the screenshot of error and steps to reproduce error


Instead of building and  copying dll to other folder you can directly reference project in your project
Right click on your project - add project reference and select tally connector project file
![image](https://user-images.githubusercontent.com/64919520/123064853-466b0380-d42c-11eb-9573-f20bcbb39109.png)
I didn't have any pre made templates you can see tests(I written tests for methods which fetch data from tally)
