### ISSUE TITLE
Possible typo error?  TallyConnector/Tally.cs#L327

### ISSUE THREAD

**Issue by zeevy** [Accounting-Companion/TallyConnector#10]
https://github.com/Accounting-Companion/TallyConnector/blob/master/TallyConnector/Tally.cs#L327

"EmployeeGroupsXml" instead of "EmployeeesXml"

**Comment by saivineeth100** [comment]
tnq @zeevy for corrections
I already worked on that [function](https://github.com/Accounting-Companion/TallyConnector/blob/7459b6f83bba7a601e2e2eac447feab9dec65629/TallyConnector/Tally.cs#L539), In todays commit that will be resolved
I changed that whole function and spitted to separate functions so that we can only query single masters(if required) instead of querying all masters

**Comment by zeevy** [comment]
Incase you have not fixed it already, these both fields seems to be interchanged in "Company.cs" model

```
        [XmlElement(ElementName = "BOOKSFROM")]
        public string StartingFrom { get; set; }

        [XmlElement(ElementName = "STARTINGFROM")]
        public string BooksFrom { get; set; }
```

**Comment by saivineeth100** [comment]
> Incase you have not fixed it already, these both fields seems to be interchanged in "Company.cs" model
> 
> ```
>         [XmlElement(ElementName = "BOOKSFROM")]
>         public string StartingFrom { get; set; }
> 
>         [XmlElement(ElementName = "STARTINGFROM")]
>         public string BooksFrom { get; set; }
> ```

Not Fixed Will Fix now
